/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package oxidationcalculator;

import javax.swing.table.TableColumn;
import oxidationcalculator.OxidationCalculator;

/**
 *
 * @author ollivanhoja
 */
public class oxidationcalculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form oxidationcalculatorUI
     */
    public oxidationcalculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();
        jCalculateButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabelWafer = new javax.swing.JLabel();
        jWaferTextField = new javax.swing.JTextField();
        jSelectWaferButton = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jEditMenu = new javax.swing.JMenu();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuItemRedo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCut = new javax.swing.JMenuItem();
        jMenuItemCopy = new javax.swing.JMenuItem();
        jMenuItemPaste = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jToolsMenu = new javax.swing.JMenu();
        jMenuItemModelEditor = new javax.swing.JMenuItem();
        jMenuItemWaferEditor = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSettings = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAddButton.setText("Add");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jRemoveButton.setText("Remove");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveButtonActionPerformed(evt);
            }
        });

        jCalculateButton.setText("Calculate");
        jCalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalculateButtonActionPerformed(evt);
            }
        });

        jTable.setModel(oxidationcalculator.OxidationCalculator.session.tableModel);
        jTable.setColumnSelectionAllowed(true);
        jScrollPane.setViewportView(jTable);
        jTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabelWafer.setText("Wafer:");

        jWaferTextField.setEditable(false);

        jSelectWaferButton.setText("Select");
        jSelectWaferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectWaferButtonActionPerformed(evt);
            }
        });

        jFileMenu.setText("File");

        jMenuItemOpen.setText("Open");
        jFileMenu.add(jMenuItemOpen);

        jMenuItemSave.setText("Save");
        jFileMenu.add(jMenuItemSave);

        jMenuItemSaveAs.setText("Save As...");
        jFileMenu.add(jMenuItemSaveAs);
        jFileMenu.add(jSeparator1);

        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemQuit);

        jMenuBar.add(jFileMenu);

        jEditMenu.setText("Edit");

        jMenuItemUndo.setText("Undo");
        jEditMenu.add(jMenuItemUndo);

        jMenuItemRedo.setText("Redo");
        jEditMenu.add(jMenuItemRedo);
        jEditMenu.add(jSeparator2);

        jMenuItemCut.setText("Cut");
        jEditMenu.add(jMenuItemCut);

        jMenuItemCopy.setText("Copy");
        jEditMenu.add(jMenuItemCopy);

        jMenuItemPaste.setText("Paste");
        jEditMenu.add(jMenuItemPaste);

        jMenuItemDelete.setText("Delete");
        jEditMenu.add(jMenuItemDelete);

        jMenuBar.add(jEditMenu);

        jToolsMenu.setText("Tools");

        jMenuItemModelEditor.setText("Oxidation Model Editor");
        jToolsMenu.add(jMenuItemModelEditor);

        jMenuItemWaferEditor.setText("Wafer Editor");
        jMenuItemWaferEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWaferEditorActionPerformed(evt);
            }
        });
        jToolsMenu.add(jMenuItemWaferEditor);
        jToolsMenu.add(jSeparator3);

        jMenuItemSettings.setText("Settings");
        jToolsMenu.add(jMenuItemSettings);

        jMenuBar.add(jToolsMenu);

        setJMenuBar(jMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jAddButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRemoveButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabelWafer)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jWaferTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSelectWaferButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 160, Short.MAX_VALUE)
                        .add(jCalculateButton))
                    .add(jScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 283, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jAddButton)
                    .add(jRemoveButton)
                    .add(jCalculateButton)
                    .add(jLabelWafer)
                    .add(jWaferTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jSelectWaferButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRemoveButtonActionPerformed

    private void jSelectWaferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectWaferButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSelectWaferButtonActionPerformed

    private void jMenuItemWaferEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWaferEditorActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new waferEditorUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItemWaferEditorActionPerformed

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void jCalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalculateButtonActionPerformed
        OxidationCalculator.session.oxs.calculate();
        jTable.updateUI();
    }//GEN-LAST:event_jCalculateButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oxidationcalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oxidationcalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oxidationcalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oxidationcalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new oxidationcalculatorUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jCalculateButton;
    private javax.swing.JMenu jEditMenu;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JLabel jLabelWafer;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCopy;
    private javax.swing.JMenuItem jMenuItemCut;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemModelEditor;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemPaste;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemRedo;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JMenuItem jMenuItemWaferEditor;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton jSelectWaferButton;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jTable;
    private javax.swing.JMenu jToolsMenu;
    private javax.swing.JTextField jWaferTextField;
    // End of variables declaration//GEN-END:variables
}
