/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package oxidationCalculatorUI;

import java.awt.Color;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import javax.swing.*;
import oxidationModel.SiWafer;
import oxidationcalculator.FileOperations.SimpleFileFilter;

/**
 *
 * @author ollivanhoja
 */
public class waferEditorUI extends javax.swing.JFrame {

    JFileChooser fc;
    SiWafer wafer;
    File waferFile;
    
    /**
     * Creates new form waferEditorUI
     */
    public waferEditorUI() {
        initComponents();
        wafer = new SiWafer(SiWafer.eWaferOrientation.mi100, 0);
        fc = new JFileChooser();
        fc.addChoosableFileFilter(new SimpleFileFilter("wafer", "Si wafer file"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelCrystalOrientation = new javax.swing.JLabel();
        jComboBoxCrystalOrientation = new javax.swing.JComboBox();
        jLabelH = new javax.swing.JLabel();
        jTextFieldH = new javax.swing.JTextField();
        jLabelHUnit = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jEditMenu = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("NameOfWafer"));
        jPanel2.setName("WaferType");

        jLabel4.setText("Picture");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCrystalOrientation.setText("Crystal orientation:");

        for (SiWafer.eWaferOrientation item : SiWafer.eWaferOrientation.values())
        jComboBoxCrystalOrientation.addItem(item);
        jComboBoxCrystalOrientation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCrystalOrientationActionPerformed(evt);
            }
        });

        jLabelH.setText("h:");

        jTextFieldH.setText("jTextField1");
        jTextFieldH.setInputVerifier(new InputVerifierDecimal());
        jTextFieldH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHActionPerformed(evt);
            }
        });

        jLabelHUnit.setText("unit");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelH)
                    .add(jLabelCrystalOrientation))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 124, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jTextFieldH, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelHUnit)
                        .addContainerGap())
                    .add(jComboBoxCrystalOrientation, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelCrystalOrientation)
                    .add(jComboBoxCrystalOrientation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelH)
                    .add(jTextFieldH, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelHUnit))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel4)
                .add(159, 159, 159))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(60, 60, 60)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 67, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jFileMenu.setText("File");

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemOpen);

        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemSave);

        jMenuItemSaveAs.setText("Save As...");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemSaveAs);
        jFileMenu.add(jSeparator1);

        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemQuit);

        jMenuBar1.add(jFileMenu);

        jEditMenu.setText("Edit");
        jMenuBar1.add(jEditMenu);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Save As... clicked
     * @param evt 
     */
    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed
        openSaveAsDialog();
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jTextFieldHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHActionPerformed
        wafer.set_h(Double.parseDouble(jTextFieldH.getText()));
    }//GEN-LAST:event_jTextFieldHActionPerformed

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    /**
     * Save clicked
     * @param evt 
     */
    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        if(waferFile != null)
            saveFile();
        else
            openSaveAsDialog();
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    /**
     * Wafer crystal orientation selected
     * @param evt 
     */
    private void jComboBoxCrystalOrientationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCrystalOrientationActionPerformed
        wafer.setOrientation((SiWafer.eWaferOrientation)jComboBoxCrystalOrientation.getSelectedItem());
    }//GEN-LAST:event_jComboBoxCrystalOrientationActionPerformed

    /**
     * File open requested
     * @param evt 
     */
    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            // Try to deserialize
            try
            {
                waferFile = fc.getSelectedFile();
                FileInputStream fin = new FileInputStream(waferFile.getAbsolutePath());
                ObjectInputStream ois = new ObjectInputStream(fin);
                wafer = (SiWafer)ois.readObject();
                ois.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Can't open wafer file.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Update fields
            jComboBoxCrystalOrientation.setSelectedItem(wafer.getOrientation());
            jTextFieldH.setText(String.valueOf(wafer.get_h()));
            jTextFieldH.isValidateRoot();
        }
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    /**
     * Input verifier for decimal value
     */
    protected class InputVerifierDecimal extends InputVerifier {
        @Override
        public boolean verify(JComponent input)
        {
            JTextField textField = (JTextField) input;
            try
            {
                double value = Double.parseDouble(textField.getText());
            }
            catch (NumberFormatException e)
            {
                textField.setBackground(Color.PINK);
                jMenuItemSave.setEnabled(false);
                jMenuItemSaveAs.setEnabled(false);
                return false;
            }
            textField.setBackground(Color.WHITE);
            jMenuItemSave.setEnabled(true);
            jMenuItemSaveAs.setEnabled(true);
            return true;
        }
    }
    
    /**
     * Save (serialize) wafer to file
     */
    private void saveFile()
    {
        wafer.set_h(Double.parseDouble(jTextFieldH.getText()));
        try
        {
            FileOutputStream fout = new FileOutputStream(waferFile.getAbsolutePath());
            ObjectOutputStream oos = new ObjectOutputStream(fout);
            oos.writeObject(wafer);
            oos.close();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
    
    private void openSaveAsDialog()
    {
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            waferFile = fc.getSelectedFile();
            if (waferFile.exists())
            {
                int response = JOptionPane.showConfirmDialog (null,
                "Overwrite existing file?","Confirm Overwrite",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.CANCEL_OPTION) return;
            }
            saveFile();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(waferEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(waferEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(waferEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(waferEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new waferEditorUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxCrystalOrientation;
    private javax.swing.JMenu jEditMenu;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCrystalOrientation;
    private javax.swing.JLabel jLabelH;
    private javax.swing.JLabel jLabelHUnit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldH;
    // End of variables declaration//GEN-END:variables
}
